/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluno;
import model.bean.Autor;
import model.bean.Editora;
import model.bean.Emprestimo;
import model.bean.Livro;
import model.bean.Professor;
import model.dao.AlunoDAO;
import model.dao.AutorDAO;
import model.dao.EditoraDAO;
import model.dao.EmprestimoDAO;
import model.dao.LivroDAO;
import model.dao.ProfessorDAO;

/**
 *
 * @author gabri
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButtonCadastroProfessor2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonCadastroAutor = new javax.swing.JButton();
        jButtonCadastroEditora = new javax.swing.JButton();
        jButtonCadastroAluno = new javax.swing.JButton();
        jButtonCadastroProfessor1 = new javax.swing.JButton();
        jButtonCadastroLivro = new javax.swing.JButton();
        jButtonEmprestimo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExibir = new javax.swing.JTable();
        jButtonExibirLivros = new javax.swing.JButton();
        jButtonExibirAluno = new javax.swing.JButton();
        jButtonExibirProfessor = new javax.swing.JButton();
        jButtonExibirEditora = new javax.swing.JButton();
        jButtonExibirAutor = new javax.swing.JButton();
        jButtonExibirEmprestimo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jButtonCadastroProfessor2.setText("Cadastrar Professor");
        jButtonCadastroProfessor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProfessor2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCadastroAutor.setText("Cadastrar Autor");
        jButtonCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroAutorActionPerformed(evt);
            }
        });

        jButtonCadastroEditora.setText("Cadastrar Editora");
        jButtonCadastroEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroEditoraActionPerformed(evt);
            }
        });

        jButtonCadastroAluno.setText("Cadastrar Aluno");
        jButtonCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroAlunoActionPerformed(evt);
            }
        });

        jButtonCadastroProfessor1.setText("Cadastrar Professor");
        jButtonCadastroProfessor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProfessor1ActionPerformed(evt);
            }
        });

        jButtonCadastroLivro.setText("Cadastrar Livro");
        jButtonCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLivroActionPerformed(evt);
            }
        });

        jButtonEmprestimo.setText("Realizar Emprestimo");
        jButtonEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestimoActionPerformed(evt);
            }
        });

        jTableExibir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTableExibir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane2.setViewportView(jTableExibir);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonExibirLivros.setText("Exibir Livros");
        jButtonExibirLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirLivrosActionPerformed(evt);
            }
        });

        jButtonExibirAluno.setText("Exibir Aluno");
        jButtonExibirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirAlunoActionPerformed(evt);
            }
        });

        jButtonExibirProfessor.setText("Exibir Professor");
        jButtonExibirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirProfessorActionPerformed(evt);
            }
        });

        jButtonExibirEditora.setText("Exibir Editora");
        jButtonExibirEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirEditoraActionPerformed(evt);
            }
        });

        jButtonExibirAutor.setText("Exibir Autor");
        jButtonExibirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirAutorActionPerformed(evt);
            }
        });

        jButtonExibirEmprestimo.setText("Exibir Emprestimos");
        jButtonExibirEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonExibirLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExibirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExibirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExibirEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExibirEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExibirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastroLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroEditora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroProfessor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExibirLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibirAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibirEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExibirEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jButtonCadastroAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroProfessor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEmprestimo)
                        .addGap(53, 53, 53))))
        );

        jMenu2.setText("Ferramentas");

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exibir");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroAlunoActionPerformed
         JanelaCadastroAlunos janelaCadastroAluno = new JanelaCadastroAlunos();
         janelaCadastroAluno.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroAlunoActionPerformed

    private void jButtonCadastroProfessor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProfessor1ActionPerformed
        JanelaCadastroProfessor janelaCadastroProf = new JanelaCadastroProfessor();
        janelaCadastroProf.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroProfessor1ActionPerformed

    private void jButtonCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLivroActionPerformed
        JanelaCadastroLivro janelaCadastroLivro = new JanelaCadastroLivro();
        janelaCadastroLivro.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroLivroActionPerformed

    private void jButtonCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroAutorActionPerformed
        JanelaCadastroAutor janelaCadastroAutor = new JanelaCadastroAutor();
        janelaCadastroAutor.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroAutorActionPerformed

    private void jButtonCadastroEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroEditoraActionPerformed
        JanelaCadastroEditora janelaCadastroEditora = new JanelaCadastroEditora();
        janelaCadastroEditora.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroEditoraActionPerformed

    private void jButtonCadastroProfessor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProfessor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroProfessor2ActionPerformed

    private void jButtonEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestimoActionPerformed
        JanelaRealizarEmprestimo janelaRealizarEmprestimo = new JanelaRealizarEmprestimo();
        janelaRealizarEmprestimo.setVisible(true);
    }//GEN-LAST:event_jButtonEmprestimoActionPerformed

    private void jButtonExibirLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirLivrosActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("ISBR");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("TÍTULO");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue("QUANTIDADE");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue("AUTOR NOME");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue("AUTOR SOBRENOME");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue("EDITORA");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue("CIDADE EDITORA");
        jTableExibir.getTableHeader().resizeAndRepaint();
        LivroDAO dao = new LivroDAO();
        dao.read();
        
        for(Livro ponteiroLivro: dao.read()){
            model.addRow(new Object[]{
                ponteiroLivro.getIsbr(),
                ponteiroLivro.getTitulo(),
                ponteiroLivro.getQtdExemplares(),
                ponteiroLivro.getAutor().getNome(),
                ponteiroLivro.getAutor().getSobrenome(),
                ponteiroLivro.getEditora().getNome(),
                ponteiroLivro.getEditora().getCidadeOrigem(),
    
            });
        }
        
        
    }//GEN-LAST:event_jButtonExibirLivrosActionPerformed

    private void jButtonExibirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirAlunoActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("RA");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("NOME");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue(" ");
        jTableExibir.getTableHeader().resizeAndRepaint();
        AlunoDAO dao = new AlunoDAO();
        
        for(Aluno ponteiroAluno: dao.read()){
            model.addRow(new Object[]{
                ponteiroAluno.getRa(),
                ponteiroAluno.getNome()  
            });
        }
    }//GEN-LAST:event_jButtonExibirAlunoActionPerformed

    private void jButtonExibirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirProfessorActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("NOME");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue("TÍTULAÇÃO");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue(" ");
        jTableExibir.getTableHeader().resizeAndRepaint();
        ProfessorDAO dao = new ProfessorDAO();
        
        for(Professor ponteiroProf: dao.read()){
            model.addRow(new Object[]{
                ponteiroProf.getCodigo(),
                ponteiroProf.getNome(),
                ponteiroProf.getTitulacao() 
            });
        }
    }//GEN-LAST:event_jButtonExibirProfessorActionPerformed

    private void jButtonExibirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirEditoraActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("NOME");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue("CIDADE ORIGEM");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue(" ");
        jTableExibir.getTableHeader().resizeAndRepaint();
        EditoraDAO dao = new EditoraDAO();
        
        for(Editora ponteiroEdi: dao.read()){
            model.addRow(new Object[]{
                ponteiroEdi.getId(),
                ponteiroEdi.getNome(),
                ponteiroEdi.getCidadeOrigem()
            });
        }
        
        
    }//GEN-LAST:event_jButtonExibirEditoraActionPerformed

    private void jButtonExibirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirAutorActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("NOME");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue("SOBRENOME");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue(" ");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue(" ");
        jTableExibir.getTableHeader().resizeAndRepaint();
        AutorDAO dao = new AutorDAO();
        
        for(Autor ponteiroAutor: dao.read()){
            model.addRow(new Object[]{
                ponteiroAutor.getId(),
                ponteiroAutor.getNome(),
                ponteiroAutor.getSobrenome()
            });
        }
        
    }//GEN-LAST:event_jButtonExibirAutorActionPerformed

    private void jButtonExibirEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirEmprestimoActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableExibir.getModel();
        while (jTableExibir.getModel().getRowCount() > 0)
            model.removeRow(0);
        
        jTableExibir.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
        jTableExibir.getColumnModel().getColumn(1).setHeaderValue("LIVRO");
        jTableExibir.getColumnModel().getColumn(2).setHeaderValue("RESPONSÁVEL");
        jTableExibir.getColumnModel().getColumn(3).setHeaderValue("CARGO RESPONSÁVEL");
        jTableExibir.getColumnModel().getColumn(4).setHeaderValue("STATUS");
        jTableExibir.getColumnModel().getColumn(5).setHeaderValue("DATA EMPRESTIMO");
        jTableExibir.getColumnModel().getColumn(6).setHeaderValue("DATA DEVOLUÇÃO");
        jTableExibir.getTableHeader().resizeAndRepaint();
        EmprestimoDAO dao = new EmprestimoDAO();
        
        for(Emprestimo ponteiroEmp: dao.read()){
            model.addRow(new Object[]{
                ponteiroEmp.getId(),
                ponteiroEmp.getLivro().getTitulo(),
                ponteiroEmp.getResponsavel(),
                ponteiroEmp.getCargoResponsavel(),
                ponteiroEmp.getStatus(),
                ponteiroEmp.getDataEmprestimo(),
                ponteiroEmp.getDataDevolucao()
            });
        }
 
    }//GEN-LAST:event_jButtonExibirEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Substance L&F".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame janelaPrincipal = new JanelaPrincipal();
                janelaPrincipal.setVisible(true);

            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastroAluno;
    private javax.swing.JButton jButtonCadastroAutor;
    private javax.swing.JButton jButtonCadastroEditora;
    private javax.swing.JButton jButtonCadastroLivro;
    private javax.swing.JButton jButtonCadastroProfessor1;
    private javax.swing.JButton jButtonCadastroProfessor2;
    private javax.swing.JButton jButtonEmprestimo;
    private javax.swing.JButton jButtonExibirAluno;
    private javax.swing.JButton jButtonExibirAutor;
    private javax.swing.JButton jButtonExibirEditora;
    private javax.swing.JButton jButtonExibirEmprestimo;
    private javax.swing.JButton jButtonExibirLivros;
    private javax.swing.JButton jButtonExibirProfessor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableExibir;
    // End of variables declaration//GEN-END:variables
}
